import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// ////// BUT WITH SSR THIS HOW YOU DO IT //////////////

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");

  const data = await res.json();

  return {
    props: {
      todos: data,
    },
  };
}

export default function Home({ todos }) {
  //////// NORMALLY THIS IS HOW YOU WILL CALL AN API AND RENDER TO A WEBPAGE ////////////

  // const [todos, setTodos] = useState([]);

  // useEffect(() => {
  //   const fetchTodos = async () => {
  //     setTimeout(async () => {
  //       const res = await fetch("https://jsonplaceholder.typicode.com/todos");

  //       const data = await res.json();
  //       setTodos(data);
  //     }, 0);
  //   };

  //   fetchTodos();
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        {todos?.length == 0 ? (
          <div>Loading....</div>
        ) : (
          todos?.map((todo) => (
            <div
              style={{
                background: "red",
                padding: "4px 10px",
                margin: "4px 0px",
                borderRadius: "5px",
                display: "block",
                alignSelf: "flex-start",
              }}
              key={todos.id}
            >
              <p>
                {todo.id}: {todo.title}
              </p>
            </div>
          ))
        )}
      </main>
    </>
  );
}
